"""
scripts/brain_audit_only.py
──────────────────────────
LAYER 3: Logic Audit.

Dry-run comparison:
1. Runs the Python Brain engine on a satellite snapshot.
2. Reads the existing 'Bet_Slips' tab from the snapshot (generated by legacy .gs).
3. Compares the two and highlights logic drift.
"""

import os
import sys
import logging
import argparse
import json
from pathlib import Path
from dotenv import load_dotenv
from supabase import create_client, Client

# Add project root to path
REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT))

from brain.data_parser import parse_upcoming_clean, parse_results_clean, parse_config_tier2, load_accumulator_config, parse_standings, load_tier1_config
from brain.contract_enforcer import build_bet_slips
from brain.game_processor import compute_magolide_predictions
from brain.game_enricher import enrich_games

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger("brain_audit")

load_dotenv()
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_KEY")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--satellite-id", required=True)
    args = parser.parse_args()

    sb: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    
    # 1. Fetch Snapshots
    res = sb.table("satellite_tab_snapshots").select("*").eq("sheet_id", args.satellite_id).execute()
    tabs = {r["tab_name"]: r["values_json"] for r in res.data}

    # 2. Run Python Brain
    upcoming = parse_upcoming_clean(tabs.get("UpcomingClean", tabs.get("Upcoming_Clean", [])))
    results = parse_results_clean(tabs.get("ResultsClean", tabs.get("Results_Clean", [])))
    config_kv = parse_config_tier2(tabs.get("Config_Tier2", []))
    standings = parse_standings(tabs.get("Standings", tabs.get("Clean", [])))
    config_tier1_kv = parse_config_tier2(tabs.get("Config_Tier1", []))
    config_tier1 = load_tier1_config(config_tier1_kv)
    
    acc_config = load_accumulator_config(config_kv)

    # Phase 2: Active computation of predictions
    computed_games = compute_magolide_predictions(upcoming, standings, results, config_tier1)

    # Phase 1 Enrichment: map computed predictions into banker/robber/sniper structs
    enriched_games = enrich_games(computed_games, acc_config)
    
    python_bet_slips = build_bet_slips(enriched_games, acc_config, "AUDIT-STAMP")

    # 3. Get Legacy .gs Bet Slips
    legacy_bet_slips = tabs.get("Bet_Slips", [])

    # 4. Compare logic parity
    compare_logic(python_bet_slips, legacy_bet_slips)

def _find_header_row_in_slips(rows):
    """Scan for the header row in a Bet_Slips 2D array."""
    for i, row in enumerate(rows):
        row_lower = [str(c).strip().lower() for c in row]
        if "home" in row_lower and "away" in row_lower:
            return i
    return -1


def _build_hm(header_row):
    """Build a simple header map {lower_col_name: index}."""
    hm = {}
    for i, cell in enumerate(header_row):
        k = str(cell or "").strip().lower()
        if k and k not in hm:
            hm[k] = i
    return hm


def _gc(row, hm, *keys):
    """Get cell value from row using header map, trying multiple key variants."""
    for k in keys:
        idx = hm.get(k)
        if idx is not None and idx < len(row):
            v = str(row[idx] or "").strip()
            if v:
                return v
    return ""


# Python BET_SLIPS_HEADERS positions (col indices)
_PY_HOME = 4
_PY_AWAY = 5
_PY_PICK = 6
_PY_TYPE = 7
_PY_BANNER_MARKER = "────────"


def _normalize_pick_key(home, away, pick, bet_type):
    """
    Normalize a pick key to a canonical form for cross-schema comparison.
    
    Handles known naming differences between Python brain and legacy .gs:
    - Type: 1H_1X2 → FIRST_HALF_1X2, SNIPER_OU → SNIPER
    - Pick: 'Q1 Over 33.5' → 'OVER', 'Q2 Under 37.5' → 'UNDER' (direction only for OU types)
    """
    # Skip header-row artifacts
    if pick.lower() in ("pick", "selection_team", "selection_text"):
        return None

    # Normalize type names
    type_map = {
        "1H_1X2": "FIRST_HALF_1X2",
        "SNIPER_OU": "SNIPER",
        "FT_OU": "FT_OU",
        "HIGH_QTR": "HIGH_QTR",
        "SNIPER_MARGIN": "SNIPER_MARGIN",
        "ROBBER": "ROBBER",
        "BANKER": "BANKER",
    }
    norm_type = type_map.get(bet_type.upper(), bet_type.upper())

    # Normalize OU pick to direction only (OVER/UNDER)
    ou_types = {"SNIPER", "SNIPER_OU", "FT_OU", "SNIPER_MARGIN"}
    norm_pick = pick
    if norm_type in ou_types or bet_type.upper() in ou_types:
        p_upper = pick.upper()
        if "OVER" in p_upper:
            norm_pick = "OVER"
        elif "UNDER" in p_upper:
            norm_pick = "UNDER"

    return f"{home} vs {away} | {norm_pick} ({norm_type})"


def _extract_picks_from_py_slips(py_slips):
    """Extract normalised pick keys from Python brain output (fixed-position schema)."""
    picks = set()
    for row in py_slips:
        if len(row) < 8:
            continue
        if _PY_BANNER_MARKER in str(row[0]):
            continue
        home = str(row[_PY_HOME] or "").strip()
        away = str(row[_PY_AWAY] or "").strip()
        pick = str(row[_PY_PICK] or "").strip()
        bet_type = str(row[_PY_TYPE] or "").strip()
        if home and away and pick and bet_type:
            key = _normalize_pick_key(home, away, pick, bet_type)
            if key:
                picks.add(key)
    return picks


def _extract_picks_from_gs_slips(gs_slips):
    """
    Extract normalised pick keys from legacy .gs Bet_Slips.

    Legacy schema (col order):
      Bet_Record_ID, Universal_Game_ID, Source_Prediction_Record_ID,
      League, Date, Home, Away, Market, Period, Selection_Side, Selection_Line,
      Selection_Team, Selection_Text, Odds, Confidence_Pct, ...

    Key columns: Home=5, Away=6, Market=7 (type), Selection_Team=11 (pick)
    """
    picks = set()
    header_idx = _find_header_row_in_slips(gs_slips)
    if header_idx < 0:
        log.warning("  ⚠️ No header row found in legacy Bet_Slips — cannot extract picks")
        return picks

    hm = _build_hm(gs_slips[header_idx])
    # Track known header-value literals to skip re-appearing section headers
    header_literals = {str(c).strip().lower() for c in gs_slips[header_idx] if c}

    for row in gs_slips[header_idx + 1:]:
        if not any(str(c).strip() for c in row):
            continue  # blank row

        # Skip repeated header rows or section-banner rows
        first_cell = str(row[0] or "").strip().lower()
        if first_cell in header_literals or first_cell.startswith("──"):
            continue

        home = _gc(row, hm, "home")
        away = _gc(row, hm, "away")
        # Pick: Selection_Team first, then Selection_Text
        pick = _gc(row, hm, "selection_team", "selection_text")
        # Bet type: Market column
        bet_type = _gc(row, hm, "market")

        if home and away and pick and bet_type:
            key = _normalize_pick_key(home, away, pick, bet_type)
            if key:
                picks.add(key)
    return picks


def compare_logic(py_slips, gs_slips):
    log.info("--- Audit Results ---")

    py_picks = _extract_picks_from_py_slips(py_slips)
    gs_picks = _extract_picks_from_gs_slips(gs_slips)

    new_picks = py_picks - gs_picks
    missing_picks = gs_picks - py_picks
    match_count = len(py_picks & gs_picks)

    log.info(f"Python picks generated : {len(py_picks)}")
    log.info(f"Legacy GS picks found  : {len(gs_picks)}")
    log.info(f"Matched picks          : {match_count}")
    log.info(f"New Picks (Python only): {len(new_picks)}")
    for p in sorted(new_picks)[:10]:
        log.info(f"  + {p}")

    log.info(f"Missing Picks (GS only): {len(missing_picks)}")
    for p in sorted(missing_picks)[:10]:
        log.info(f"  - {p}")

    if match_count > 0 and len(missing_picks) == 0:
        log.info("🎯 PERFECT LOGIC PARITY DETECTED.")
    elif match_count > 0:
        pct = 100 * match_count / max(len(gs_picks), 1)
        log.info(f"⚠️ PARTIAL PARITY: {pct:.0f}% of GS picks matched.")
        log.warning("Review missing picks — likely confidence threshold or column mapping differences.")
    elif len(gs_picks) == 0 and len(py_picks) == 0:
        log.warning("⚠️ NO PICKS on either side — check data quality.")
    else:
        log.warning("⚠️ LOGIC DRIFT DETECTED: No picks matched. Review pick generation differences.")

if __name__ == "__main__":
    main()
